version: 2.1
jobs:
  build-builder:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build
          command: docker build -f ./ops/docker/Dockerfile.builder -t mslipper/optimism-builder:$CIRCLE_SHA1 .
      - run:
          name: Push
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mslipper/optimism-builder:$CIRCLE_SHA1

  build-l2geth:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker build -f ./ops/docker/Dockerfile.geth \
              -t mslipper/optimism-l2geth:$CIRCLE_SHA1 \
              --build-arg TAG=$CIRCLE_SHA1 \
              .
      - run:
          name: Push
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mslipper/optimism-l2geth:$CIRCLE_SHA1

  build-dtl:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker build -f ./ops/docker/Dockerfile.data-transport-layer \
              -t mslipper/optimism-dtl:$CIRCLE_SHA1 \
              --build-arg TAG=$CIRCLE_SHA1 \
              .
      - name: Push
        command: |
          echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push mslipper/optimism-l2geth:$CIRCLE_SHA1


  build-itests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: 
          name: Build
          command: |
            docker build -f ./ops/docker/Dockerfile.integration-tests \
              -t mslipper/optimism-integration-tests:$CIRCLE_SHA1 \
              --build-arg TAG=$CIRCLE_SHA1 \
              .

workflows:
  build-monorepo:
    jobs:
      - build-builder:
          context: optimism
      - build-l2geth:
          context: optimism
      - build-dtl:
          context: optimism
          requires:
            - build-builder
      - build-itests:
          context: optimism
          requires:
            - build-builder
