version: 2.1
jobs:
  build-builder:
    machine:
      image: ubuntu-2004:202107-02
      docker_layer_caching: true
      resource_class: xlarge
    steps:
      - checkout
      - run:
          name: Build
          command: docker build -f ./ops/docker/Dockerfile.builder -t mslipper/optimism-builder:$CIRCLE_SHA1 .
      - run:
          name: Push
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mslipper/optimism-builder:$CIRCLE_SHA1

  build-l2geth:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker build -f ./ops/docker/Dockerfile.geth \
              -t mslipper/optimism-l2geth:$CIRCLE_SHA1 \
              --build-arg TAG=$CIRCLE_SHA1 \
              .
      - run:
          name: Push
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mslipper/optimism-l2geth:$CIRCLE_SHA1

  build-gas-oracle:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker build -f ./ops/docker/Dockerfile.gas-oracle \
              -t mslipper/optimism-gas-oracle:$CIRCLE_SHA1 \
              --build-arg TAG=$CIRCLE_SHA1 \
              .
      - run:
          name: Push
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mslipper/optimism-gas-oracle:$CIRCLE_SHA1

  build-dtl:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker build -f ./ops/docker/Dockerfile.data-transport-layer \
              -t mslipper/optimism-dtl:$CIRCLE_SHA1 \
              --build-arg TAG=$CIRCLE_SHA1 \
              .
      - run:
          name: Push
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mslipper/optimism-dtl:$CIRCLE_SHA1

  build-deployer:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker build -f ./ops/docker/Dockerfile.deployer \
              -t mslipper/optimism-deployer:$CIRCLE_SHA1 \
              --build-arg TAG=$CIRCLE_SHA1 \
              .
      - run:
          name: Push
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mslipper/optimism-deployer:$CIRCLE_SHA1


  build-batch-submitter:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            docker build -f ./ops/docker/Dockerfile.batch-submitter \
              -t mslipper/optimism-batch-submitter:$CIRCLE_SHA1 \
              --build-arg TAG=$CIRCLE_SHA1 \
              .
      - run:
          name: Push
          command: |
            echo "$DOCKER_HUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push mslipper/optimism-batch-submitter:$CIRCLE_SHA1


  build-itests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run: 
          name: Build
          command: |
            docker build -f ./ops/docker/Dockerfile.integration-tests \
              -t mslipper/optimism-integration-tests:$CIRCLE_SHA1 \
              --build-arg TAG=$CIRCLE_SHA1 \
              .


  run-itests:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Bring the stack up
          command: |
            cd ./ops
            docker-compose build l1_chain
            TAG=$CIRCLE_SHA1 docker-compose -f ./docker-compose-itests.yml up --no-build -d
      - run: 
          name: Wait for the sequencer
          command: |
            cd ./ops && ./scripts/wait-for-sequencer.sh
      - run:
          name: Run the integration tests
          command: |
            cd ops && TAG=$CIRCLE_SHA1 docker-compose -f ./docker-compose-itests.yml run --no-build integration_tests


workflows:
  monorepo-itests:
    jobs:
      - build-builder:
          context: optimism
      - build-l2geth:
          context: optimism
      - build-gas-oracle:
          context: optimism
      - build-dtl:
          context: optimism
          requires:
            - build-builder
      - build-deployer:
          context: optimism
          requires:
            - build-builder
      - build-batch-submitter:
          context: optimism
          requires:
            - build-builder
      - build-itests:
          context: optimism
          requires:
            - build-builder
      - run-itests:
          context: optimism
          requires:
            - build-builder
            - build-l2geth
            - build-gas-oracle
            - build-dtl
            - build-deployer
            - build-batch-submitter
            - build-itests
