version: 2.1
jobs:
  build-builder:
    machine:
      image: ubuntu-2004:202107-02
      resource_class: large
    steps:
      - checkout
      - run: docker build -f ./ops/docker/Dockerfile.builder -t ethereumoptimism/builder:$CIRCLE_SHA1 .

workflows:
  build-monorepo:
    jobs:
      - build-builder
