version: 2.1
jobs:
  build-builder:
    machine:
      image: ubuntu-2004:202107-02
      resource_class: large
      docker_layer_caching: true
    steps:
      - checkout
      - run: docker build -f ./ops/docker/Dockerfile.builder -t ethereumoptimism/builder:$CIRCLE_SHA1 .
  build-itests:
    machine:
      image: ubuntu-2004:202107-02
      resource_class: large
      docker_layer_caching: true
    steps:
      - checkout
      - run: |
          docker build -f ./ops/docker/Dockerfile.integration-tests \
            -t ethereumoptimism/integration-tests:$CIRCLE_SHA1 \
            --build-arg TAG=$CIRCLE_SHA1 \
            .
workflows:
  build-monorepo:
    jobs:
      - build-builder
      - build-itests:
        requires:
          - build-builder
