ARG REGISTRY=docker.io
ARG TAG=latest
FROM ${REGISTRY}/mslipper/optimism-builder:${TAG}

WORKDIR /optimism/integration-tests

RUN yarn workspace @eth-optimism/integration-tests build:integration

COPY ./ops/scripts/integration-tests.sh ./
CMD ["yarn", "test:integration"]
