ARG REGISTRY=docker.io
ARG TAG=latest
FROM ${REGISTRY}/mslipper/optimism-builder:${TAG} as builder

WORKDIR /optimism/packages/batch-submitter

# copy this over in case you want to run alongside other services
COPY ./ops/scripts/batches.sh .
CMD ["npm", "run", "start"]
