ARG REGISTRY=docker.io
ARG TAG=latest
FROM ${REGISTRY}/mslipper/optimism-builder:${TAG} as builder

WORKDIR /optimism/packages/data-transport-layer

# copy this over in case you want to run alongside other services
COPY ./ops/scripts/dtl.sh .
ENTRYPOINT ["node", "dist/src/services/run.js"]
